require('dotenv').config();
const express = require('express');
const cors = require('cors');
const twilio = require('twilio');

const app = express();
app.use(cors({
  origin: '*',
  methods: ['GET', 'POST', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));
app.use(express.json({ limit: '50mb' }));

const twilioClient = twilio(process.env.TWILIO_SID || 'AC_PLACEHOLDER', process.env.TWILIO_AUTH_TOKEN || 'PLACEHOLDER');

// AWS Bedrock API Routes
const { rateLimiter } = require('./middleware/rateLimiter');
const apiRoutes = require('./routes/api');

// Apply rate limits to protect AWS costs
app.use('/api/process-query', rateLimiter(50));
app.use('/api/scan-document', rateLimiter(50));
app.use('/api/read-notice', rateLimiter(50));
app.use('/api/context-chat', rateLimiter(50));

// Mount the AWS Bedrock & S3 routes
app.use('/api', apiRoutes);

// 5. Geo Route (Mocked for Demo)
app.post('/api/geo-route', (req, res) => {
  const { lat, lng, officeType } = req.body;
  // Mock Geo Routing response
  res.json({
    officeName: "Mocked Local BDO Office",
    address: "Block Development Office, Sample Area",
    mapsLink: "https://maps.google.com/?q=" + lat + "," + lng,
    distanceKm: 2.5,
    workingHours: "10:00 AM - 4:00 PM (Mon-Sat)",
    avoidDays: "Sundays, Public Holidays",
    documentsToCarry: ["Aadhaar", "Recent Photographs"]
  });
});

// 7. Twilio WhatsApp
app.post('/api/send-whatsapp', async (req, res) => {
  const { phoneNumber, message } = req.body;
  if (process.env.TWILIO_SID === 'AC_PLACEHOLDER' || !process.env.TWILIO_SID) {
    return res.json({ success: true, sid: "mock_sid_for_testing" });
  }
  try {
    const response = await twilioClient.messages.create({
      body: `*Bharat Seva Action Plan*\n\n${message}\n\n_Generated by AI for Rural India_`,
      from: 'whatsapp:+14155238886',
      to: `whatsapp:${phoneNumber}`
    });
    res.json({ success: true, sid: response.sid });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Bharat Seva Backend running on http://localhost:${PORT}`);
});